// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzqriohyfazftfulwcuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cXJpb2h5ZmF6ZnRmdWx3Y3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjcwNDAsImV4cCI6MjA2OTY0MzA0MH0.Zj8e5s0rZCHxJEkqpxMzHDEO-doBkiwzi7ErLHl9F28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});